### ISSUE TITLE
Check bech-32 validity

### ISSUE THREAD

**Issue by NetOperatorWibby** [neuenet/handshake-regex#1]
Currently, [this module](https://github.com/bitcoinjs/bech32) throws an error instead of boolean so we'd want to wrap that check in a try/catch, with the `false` boolean response in the catch.

```ts
// something like this
try {
  decoded = bech32.decode(suppliedAddress);
} catch (error) {
  decoded = false;
}
```

**Comment by NetOperatorWibby** [comment]
This would be an additional option.

```ts
dap("hs1q98ddwl2lcpnnzfvvrqad80qu97w0q72cyq2uy3", "bech");
```

**Comment by NetOpWibby** [comment]
I think [this commit](https://github.com/neuenet/handshake-regex/commit/7e6a06517764cd9bd750d2c3171df3e54d9f3594) also solves this issue.
