### ISSUE TITLE
Version 0 addresses can have 20 or 32 bytes of data

### ISSUE THREAD

**Issue by pinheadmz** [neuenet/handshake-regex#2]
This regex:

https://github.com/neuenet/handshake-regex/blob/1bf99630529cb61dcd06bffd1006317a07fb932a/src/index.ts#L6

Is missing a few tweaks. First of all, version 0 HNS addresses can be 42 OR 62 characters long:

```
// both valid
hs1qk2g3zx3hr479nsq507nzgx5q3us60ewdp8jksj5hpkfumulqhy3qgsxwey
hs1qphmqky96jhyet3f5ch7d0q8q4yxzy0w0rz5ut3
```

That should be good enough for now. Our bech32 addresses also always include a `"1"` which in [BIP173](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#bech32) is called the "separator". That should be the only `"1"` in the entire string, otherwise it is invalid.

In the future, we may deploy a different address version which will change the fourth character of the string. Right now all HNS address have a `"q"` there indicating version 0, but if we ever adapt Taproot (for example) and need a new address version, that character will change -- and then the corresponding data length may also change. So to summarize, if the address starts with `hs1q` there will be either 38 or 58 more characters following. In the future you may see addresses that start with `hs1p` -- and then we'll have to wait and see what the spec is for those when it arrives.

You can also check out the `Address` module in hsd, or maybe even deploy part of that code to be totally sure the address validation is correct.

**Comment by NetOpWibby** [comment]
That’s useful info, thanks! I’ll add in the next version.

**Comment by Falci** [comment]
> version 0 HNS addresses can be 42 OR 62 characters long

Not sure about that @pinheadmz. Nulldata address can have from 2 to 40 bites:

```javascript
Address.fromNulldata(Buffer.alloc(2)); // hs1lqqqqhuxwgy
Address.fromNulldata(Buffer.alloc(40)); // hs1lqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqwwtqjv
```

**Comment by pinheadmz** [comment]
@Falci nulldata addresses are not version `0` they are version `31` -- but that's a good point, they are also currently standard in the HNS network and you'll notice the fourth character is always `l` (lower-case L) indicating version `31`. I'm not sure what kind of services are using this regex but nulldata outputs are unsepndable and should probably be ignored except in special use cases.

**Comment by NetOpWibby** [comment]
Hmm, interesting. I'll add a bit to ignore them then, and also update the README to explain the situation.

**Comment by Falci** [comment]
My bad.
```
<Address: version=31 str=hs1lqqqqhuxwgy>
```
