### ISSUE TITLE
Regex insufficient

### ISSUE THREAD

**Issue by rithvikvibhu** [neuenet/handshake-regex#3]
The address isn't just a random set of chars, it also includes a checksum (and possibly other restrictions I don't know of).

I feel that hsd's [`Address`](https://github.com/handshake-org/hsd/blob/master/lib/primitives/address.js) (which uses bech32+more) does a good job. Any reason why this isn't used?

An example (only the last char is changed):
```js
> new hsd.Address('hs1q98ddwl2lcpnnzfvvrqad80qu97w0q72cyq2uy3')
<Address: version=0 str=hs1q98ddwl2lcpnnzfvvrqad80qu97w0q72cyq2uy3>
> new hsd.Address('hs1q98ddwl2lcpnnzfvvrqad80qu97w0q72cyq2uy2')
Uncaught Error: Encoding failed
```

While this library's regex matches both:
```js
>'hs1q98ddwl2lcpnnzfvvrqad80qu97w0q72cyq2uy3'.match(/hs1[a-z02-9]{39,87}/)
<["hs1q98ddwl2lcpnnzfvvrqad80qu97w0q72cyq2uy3", index: 0, input: "hs1q98ddwl2lcpnnzfvvrqad80qu97w0q72cyq2uy3", groups: undefined]
>'hs1q98ddwl2lcpnnzfvvrqad80qu97w0q72cyq2uy2'.match(/hs1[a-z02-9]{39,87}/)
<["hs1q98ddwl2lcpnnzfvvrqad80qu97w0q72cyq2uy2", index: 0, input: "hs1q98ddwl2lcpnnzfvvrqad80qu97w0q72cyq2uy2", groups: undefined]
```

**Comment by Falci** [comment]
That's kind of ok. 
This lib is suppose to be a hns address regex, which means it can't fully validate the address, but quickly spot invalid addresses.

This lib can be used for light web clients (in bites) where the connection maybe a problem. While a backend should fully validate address using something else.

Try to see this way: if the regex says invalid, it's definitely invalid. If it say valid, it could be a false-positive.

**Comment by NetOpWibby** [comment]
Yeah, this module is intended for quick front-end checks.

**Comment by rithvikvibhu** [comment]
Okay, maybe mention this under Notes in the readme?

**Comment by NetOpWibby** [comment]
Updated the README
