### ISSUE TITLE
Support other networks

### ISSUE THREAD

**Issue by Falci** [neuenet/handshake-regex#4]
It could be interesting an option where we can set the network (`main`, `testnet`, `regtest` or `simnet`). Of course, default to `main`.

**Comment by NetOpWibby** [comment]
What sort of changes arise when setting different networks. Does the address format change?

**Comment by rithvikvibhu** [comment]
The address prefix changes:
```js
main.addressPrefix = 'hs';
testnet.addressPrefix = 'ts';
regtest.addressPrefix = 'rs';
simnet.addressPrefix = 'ss';
```

Taken from https://github.com/handshake-org/hsd/blob/master/lib/protocol/networks.js
